server:
  port: 18888
spring:
  ai:
    deepseek:
      api-key: api_key
      chat:
        options:
          model: deepseek-chat
        enabled: true
        base-url: https://api.deepseek.com/v1
        api-key: api_key
    mcp:
      client:
        sse:
          connections:
            server1:
              url: http://localhost:19999
        stdio:
          servers-configuration: classpath:mcp-servers.json

logging:
  level:
    org.springframework.ai: TRACE
