server:
  port: 17777
# Using spring-ai-starter-mcp-server
spring:
  main:
    banner-mode: off
    web-application-type: none
  ai:
    mcp:
      server:
        name: stdio-mcp-server
        version: 1.0.0
        type: SYNC
        stdio: true
        enabled: true
logging:
  pattern:
    console: